{
  "hash": "905b84b972e1571fdef0b42e9c3effe1",
  "result": {
    "markdown": "---\ntitle: \"Statistik och dataanalys I, 15 hp \"\nsubtitle: \"Datorlaboration 2\"\nauthor: \n  - Byt ut mot namnet på student 1\n  - Byt ut mot namnet på student 2\n  - Byt ut mot namnet på student 3\ndate: last-modified\nformat: \n  html:\n    self-contained: true\ntoc: true\nexecute:\n  error: false\nlanguage: \n  title-block-author-single: \" \"\ntoc-title-document: \"Innehåll\"\ncrossref-fig-title: \"Figur\"\ntheme: Superhero\neditor: visual\n---\n\n\n\n::: callout-warning\nDen här labben förutsätter att följande paket finns installerade:\n\n-   `openxlsx`\n\n-   `mosaic`\n\nPaket kan installeras via kommandot `install.packages('packagename')`, där `'packagename'` är namnet på paketet, t.ex `'mosaic'`.\n:::\n\n## Introduktion\n\n> I den här datorlabben kommer vi att titta på hur fördelningar för olika typer av variabler kan beskrivas numeriskt och grafiskt.\n\n#### 💪 Uppgift 0.3\n\nLägg till en ny code chunk och ställ in 'working directory' till den nya mappen genom att följa anvisningarna från [Lab 1](https://statisticssu.github.io/SDA1/datorlab/lab1/DatorLab1.html#st%C3%A4lla-in-arbetsmappen-working-directory-i-r).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fyll i lösning för Uppgift 0.3 här\n```\n:::\n\n\n## 1. Skapa tabeller för kategoriska variabler\n\nInstallerar några paket som ska användas för laborationen.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#install.packages(\"openxlsx\") # Kommentera bort denna rad om redan har openxlsx installerat från Lab 1\n#install.packages(\"mosaic\") # Kommentera bort denna rad efter att du kört Quarto-filen första gången\nsuppressMessages(library(openxlsx))\nsuppressMessages(library(mosaic))\n```\n:::\n\n\nVi läser in datamaterialet direkt från webben:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntitanic = read.xlsx(\"https://github.com/StatisticsSU/SDA1/raw/main/datorlab/lab2/Chapter_3.xlsx\", sheet = \"Titanic\")\n```\n:::\n\n\n#### 💪 Uppgift 1.1\n\nÄndra koden ovan så `read.xlsx()` istället läser in filen 'Chapter_3.xlsx' från din dator.\n\nVariabeln `Survived` i datasetet är en kategorisk variabel med två kategorier `Dead` och `Alive`. När en variabel bara har två kategorier brukar man också säga **binär variabel**. Man kan räkna antalet observationer som tillfaller varje kategori och på så sätt skapa en frekvenstabell med funktionen `tally()` i `mosaic`-paketet enligt nedan.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_survived <- tally(~ Survived, data = titanic)\ntab_survived\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSurvived\nAlive  Dead \n  712  1496 \n```\n:::\n:::\n\n\nGenom att lägga till argumentet `format = proportion` i `tally()` räknas de relativa frekvenserna istället.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntally(~ Survived, data = titanic, format = \"proportion\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSurvived\n    Alive      Dead \n0.3224638 0.6775362 \n```\n:::\n:::\n\n\nVill man ha detta presenterat i procent kan man enkelt skriva `format = percent` istället för `proportion`\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntally(~ Survived, data = titanic, format = \"percent\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSurvived\n   Alive     Dead \n32.24638 67.75362 \n```\n:::\n:::\n\n\nAlltså överlevde endast 32.2% av de som befann sig på Titanic, medan 67.8% dog.\n\n#### 💪 Uppgift 1.1\n\nVariabeln `Class` talar om biljettklass passageraren reste med (1:a, 2:a, 3:e eller Crew (besättning)). Presentera det totala antalet inom varje biljettklass. Vilken kategori är störst?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n\n#### 💪 Uppgift 1.2\n\nBeräkna den relativa frekvensen (i procent) inom varje biljettklass.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n\n## 2. Grafisk illustration av kategoriska variabler\n\nEtt enkel pajdiagram fås genom koden:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable_rel_freq = tally(~ Survived, data = titanic, format = \"proportion\")\npie(x = table_rel_freq)\n```\n\n::: {.cell-output-display}\n![](DatorLab2Simple_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nOch här är en lite mer informativt diagram:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrel_frequencies = round(table_rel_freq, 2) # round the numbers to two decimals\nrel_frequencies\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSurvived\nAlive  Dead \n 0.32  0.68 \n```\n:::\n\n```{.r .cell-code}\ncategory_names = names(table_rel_freq)\ncategory_names\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Alive\" \"Dead\" \n```\n:::\n\n```{.r .cell-code}\ncolors = c(\"lightblue\", \"purple\")\npie(x =  table_rel_freq, labels = rel_frequencies, col = colors)\nlegend(\"topright\", legend = category_names, fill = colors)\n```\n\n::: {.cell-output-display}\n![](DatorLab2Simple_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n#### 💪 Uppgift 2.1\n\nSkapa ett pajdiagram av variabeln `Class` i titanic. Använd dig gärna av uträkningarna från Uppgift 1.2 för att skapa grafen. Välj själv om du vill illustrera det som andelar eller i procent.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n\n#### 💪 Uppgift 2.2\n\nVad är det för fel på denna graf?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrel_frequencies = c(0.1, 0.9)\ncategory_names = names(table_rel_freq)\ncolors = c(\"lightblue\", \"purple\")\npie(x =  table_rel_freq, labels = rel_frequencies, col = colors)\nlegend(\"topright\", legend = category_names, fill = colors)\n```\n\n::: {.cell-output-display}\n![](DatorLab2Simple_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbargraph(~ Survived, data = titanic, type = \"proportion\")\n```\n\n::: {.cell-output-display}\n![](DatorLab2Simple_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nx_axis_title = \"Survival\"\ny_axis_title = \"Frequency\"\nlength_y_axis = c(0, 0.80)\ncolors = c(\"lightblue\", \"purple\")\n\nbargraph(~ Survived, data = titanic, type = \"proportion\", \n         xlab = x_axis_title, ylab = y_axis_title, ylim = length_y_axis, col = colors)\n```\n\n::: {.cell-output-display}\n![Relative frequency of Survival on the Titanic](DatorLab2Simple_files/figure-html/fig-andelar-1.png){#fig-andelar width=672}\n:::\n:::\n\n\n#### 💪 Uppgift 2.3\n\nJustera diagrammet nedan så att det ser mer presentabelt ut. Byt också ut färgerna mot två andra bland [R's standardfärger](https://r-graph-gallery.com/42-colors-names.html).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx_axis_title = \"Survival\"\ny_axis_title = \"Frequency\"\nlength_y_axis = c(0, 0.1)\n\nbargraph(~ Survived, data = titanic, type = \"proportion\",  \n         xlab = x_axis_title, ylab = y_axis_title, ylim = length_y_axis, col = colors)\n```\n\n::: {.cell-output-display}\n![](DatorLab2Simple_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n#### 💪 Uppgift 2.4\n\nRätta till felet i följande diagram:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx_axis_title = \"Survival\"\ny_axis_title = \"Frequency\"\n\nbargraph(~ Survived, data = titanic, type = \"count\", \n         xlab = x_axis_title, ylab = y_axis_title, col = colors)\n```\n\n::: {.cell-output-display}\n![](DatorLab2Simple_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n#### 💪 Uppgift 2.5\n\nSkapa ett stapeldiagram med funktionen `bargraph()` för variabeln `Class` i titanic. Använd relativa frekvenser denna gång.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n\n## 3. Dataset som består av saknade värden\n\nVi tar bort saknade värde i variabeln Age:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlength(titanic$Age) # number of observations originally\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2208\n```\n:::\n\n```{.r .cell-code}\nAge = na.omit(titanic$Age)\nlength(Age) # the number of observations when missing values are removed\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2205\n```\n:::\n:::\n\n\n#### 💪 Uppgift 3.1\n\nDefiniera en ny variabel `Paid` från kolumnen `Paid` i datasetet `titanic` på liknande sätt som ovan. Rensa bort eventuella saknade värden med funktionen `na.omit()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n\n## 4. Grafisk presentation av numeriska variabler\n\nHär är ett exempel med funktionen `histogram()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhistogram(~ Age, data = titanic, col = \"navyblue\")\n```\n\n::: {.cell-output-display}\n![Distribution of Age onboard the Titanic](DatorLab2Simple_files/figure-html/fig-hist-1.png){#fig-hist width=672}\n:::\n:::\n\n\nOch här med density\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndensityplot(~ Age, data = titanic, col = \"navyblue\")\n```\n\n::: {.cell-output-display}\n![Distribution of Age onboard the Titanic](DatorLab2Simple_files/figure-html/fig-density-1.png){#fig-density width=672}\n:::\n:::\n\n\n#### 💪 Uppgift 4.1\n\nRita ett histogram likt ovan, med samma variabel men med en annan färg. Testa dig fram med `breaks` argumentet tills du hittar vad du tycker är ett passande antal staplar. Rita sedan ett till likadant histogram men använd dig av Sturges regel denna gång för att bestämma hur många staplar som ska användas. Ser histogrammet bättre ut än det du ritade utan Sturges regel?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n\n#### 💪 Uppgift 4.2\n\nRita ett histogram över variabeln `Paid`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n\n#### 💪 Uppgift 4.3\n\nVilket mått av medelvärdet eller medianen beskriver centralpunkten i fördelningen för `Paid` bäst?\n\n#### 💪 Uppgift 4.4\n\nRita täthetsplottar för variablerna `Age` och `Paid`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhist_Age = hist(x = Age,  col = \"coral\")\n```\n\n::: {.cell-output-display}\n![](DatorLab2Simple_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n\n```{.r .cell-code}\nfrequencies = hist_Age$count\nfrequencies\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1]  62  38  33 271 432 400 321 264 158 103  49  37  28   5   4\n```\n:::\n:::\n\n\nI det första argumentet i funktionen `barplot()` lägger vi in frekvenserna som nyss räknades ut. Det andra argumentet `names.arg` är till för att namnge de olika åldersintervallen ovan, på x-axeln. Argumentet `las = 3` gör endast så att texten på x-axeln blir lodrät.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAge_Intervals = c(\"0-4\", \"5-9\", \"10-14\", \"15-19\", \"20-24\", \"25-29\", \"30-34\", \n              \"35-39\", \"40-44\", \"45-49\", \"50-54\", \"55-59\", \"60-64\", \"65-69\",\n              \"70-74\")\n\nbarplot(frequencies, names.arg = Age_Intervals, las = 3,\n        main = \"Frequency of Age onboard the Titanic\")\n```\n\n::: {.cell-output-display}\n![](DatorLab2Simple_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\nHistogrammet som skapades innan går alltså i princip att göra om till ett stapeldiagram, där höjden på stapeln illustrerar hur många observationer det är som tillfaller varje ålderskategori. :::\n\n## 5. Numerisk beskrivning av kvantitiva variabler\n\nOm man använder sig av en frekvenstabell för en numerisk variabel riskerar man i värsta fall att få en tabell som är lika lång som antal observationer man har. Kanske har man inte ens ett enda fall där två olika observationer har samma värden. Därför används ofta andra beskrivande mått. Bland de viktigaste är **lägesmåtten** som fångar fördelningens mittpunkt\n\n-   medelvärde\n-   median\n\noch spridningsmåtten som mäter variationen kring fördelningens mittpunkt:\n\n-   varians\n-   standardavvikelse\n-   variationsbredd (`range` på engelska: skillnaden mellan maximum och minimumvärdet)\n-   Interkvartila avståndet (IQR).\n\nFunktionen `favstats()` i `mosaic`-paketet beräknar dessa mått:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfavstats(~ Age, data = titanic)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  min Q1 median Q3 max     mean       sd    n missing\n 0.08 22     29 37  74 30.14689 11.97386 2205       3\n```\n:::\n:::\n\n\nFunktionen räknar ut olika fördelningsmått, såsom minimumvärdet, maximumvärdet, första och tredje kvartilen samt medelvärdet och medianen. Både medelvärdet och medianen är mått på en fördelnings mittpunkt men hur lämpliga de är som mått beror på fördelningens utseende. Vi ser även att funktionen också skriver ut hur många värden datasetet består av och antalet saknade värden.\n\nIbland vill man dock inte skriva ut all denna information för en variabel. I Datorlaboration 1 använde vi oss av funktionen `mean()` för att räkna ut medelvärdet av en variabel. Några andra vanliga funktioner utöver dessa är `var()` och `sd()`. Matematiskt motvaras dessa tre funktioner av: \\begin{align}\\nonumber\n\\overline{y}= \\frac{1}{n} \\sum_{i=1}^n y_i \\\\ \\nonumber\ns^2 =\\frac{\\sum_{i=1}^n(y_i-\\overline{y})^2}{n-1}\n\\end{align} och \\begin{align}\ns = \\sqrt{s^2}\n\\end{align}\n\n#### 💪 Uppgift 5.1\n\nAnvänd funktionerna ovan för att räkna ut medelvärdet, variansen och standardavvikelsen för variabeln `Age`. Kan man räkna ut standardavvikelsen på något annat sätt i R?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n\n#### 💪 Uppgift 5.2\n\nRäkna ut det variationsbredden samt det interkvartila avståndet av variabeln `Age` från utskriften vi fick från funktionen `favstats()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n\n## 6. Indexering och upprepning (loopar)\n\nLåt oss titta på ett dataset över UFC's top 10 kampsportsutövare i Welterweight klassen bland män (december 2022). Nedan matas värdena in i vektorer och sedan sätts alla variabler ihop i en och samma tabell med funktionen `data.frame()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Defining variables:\nName = c(\"Kamaru Usman\", \"Colby Covington\", \"Khamzat Chimaev\", \"Belal Muhammed\",\n         \"Gilbert Burns\",\"Stephen Thompson\", \"Geoff Neal\", \"Sean Brady\", \n         \"Vicente Luque\", \"Shavkat Rakhmanov\" )\nRank = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)\nWins_by_knockout = c(9, 4, 6, 5, 6, 8, 9, 3, 11, 8)\nTakedown_avg = c(3.01, 4.05, 3.98, 2.19, 2, 0.27, 0.59, 2.8, 0.51, 2.31)\nAge_fighters = c(35,34,27, 34, 35, 39, 31, 29, 30, 27)\n\n# Creating a dataframe with all the variables just defined above:\nUFC = data.frame(Name, Rank, Wins_by_knockout, Takedown_avg, Age_fighters)\nUFC\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                Name Rank Wins_by_knockout Takedown_avg Age_fighters\n1       Kamaru Usman    1                9         3.01           35\n2    Colby Covington    2                4         4.05           34\n3    Khamzat Chimaev    3                6         3.98           27\n4     Belal Muhammed    4                5         2.19           34\n5      Gilbert Burns    5                6         2.00           35\n6   Stephen Thompson    6                8         0.27           39\n7         Geoff Neal    7                9         0.59           31\n8         Sean Brady    8                3         2.80           29\n9      Vicente Luque    9               11         0.51           30\n10 Shavkat Rakhmanov   10                8         2.31           27\n```\n:::\n:::\n\n\nDatasetet består av fem stycken variabler och är sorterat efter `Rank`. I Lab 1 tittade vi lite på **indexering** och detta bygger vidare på det. Låt säga att vi vill veta vad åldern är för den 6:e rankade utövaren. I detta fall är datasetet väldigt litet och man kan genast identifiera alla individer. Ibland har vi dataset som är väldigt stora och då kan man behöva använda sig av indexering för att få ut information om en enskild (eller ett fåtal) observationer av intresse. För att ta reda på åldern på den 6:e rankade utövaren kan man då använda sig av koden `UFC[6, 5]`. Där siffran till vänster om kommatecknet i hakparantesen anger radtalet och siffran till höger om kommatecknet anger kolumntalet. Detta ger oss svaret 39.\n\n#### 💪 Uppgift 6.1\n\nAnvänd indexering för att skriva ut hur många wins by knockout Gilbert Burns har haft.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n\n#### 💪 Uppgift 6.2\n\nAnvänd indexering för att skriva ut all information om Kamaru Usman (dvs den första raden). \\[Ledtråd: om man inte skriver något alls efter kommatecknet i indexeringen får man *alla* värden i den raden\\]\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n\n#### 💪 Uppgift 6.3\n\nAnvänd indexering för att skriva ut alla värden för variabeln `Takedown_avg` (dvs den 4:e kolumnen).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n\n#### 💪 Uppgift 6.4\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfor (i in 1:10){\n  print(i)\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1\n[1] 2\n[1] 3\n[1] 4\n[1] 5\n[1] 6\n[1] 7\n[1] 8\n[1] 9\n[1] 10\n```\n:::\n:::\n\n\nAnvänd loopen ovan men byt ut indexvariabeln `i` till `k` istället. Kör sedan loopen. Vad är det som händer?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n\n#### 💪 Uppgift 6.5\n\nAnvänd återigen loopen i exemplet ovan. Men ändra variabeln `i`s definitionsmängd från 1:10 till 24:33.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n\n#### 💪 Uppgift 6.6\n\nGör på samma vis som i övningen ovan men ändra nu definitionsmängden från 1:10 till -3:5\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n\n#### 💪 Uppgift 6.7\n\nAnvänd en `for`-loop för att skriva ut varje värde på variabeln `Wins_by_knockout`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n\nDen introduktionen till loopar kan räcka för tillfället. Men om du tyckte det var intressant kan du fortsätta läsa lite mer om loopar nedan.\n\n#### 💪 Uppgift 6.8\n\nFunktionen `sum()` i R kan användas för att summera numeriska värden i en vektor. Använd denna funktion för att räkna ut medelvärdet för variabeln `Age_fighters` ovan.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n\n\n::: callout-tip\nMedelvärdet ges av formeln: \\begin{align}\n\\nonumber \\overline{y}= \\frac{1}{n} \\sum_{i=1}^n y_i\n\\end{align}\n:::\n\n#### 💪 Uppgift 6.9\n\nAnvänd en `for`-loop för att räkna ut medelvärdet för variabeln `Age_fighters`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your code here\n```\n:::\n",
    "supporting": [
      "DatorLab2Simple_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}